// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Azure.DataApiBuilder.Config.ObjectModel;

/// <summary>
/// Describes the GraphQL settings specific to an entity.
/// </summary>
/// <param name="Singular">The singular type name for the GraphQL object. If none is provided this will be generated by the Entity key.</param>
/// <param name="Plural">The pluralisation of the entity. If none is provided a pluralisation of the Singular property is used.</param>
/// <param name="Enabled">Indicates if GraphQL is enabled for the entity.</param>
/// <param name="Operation">When the entity maps to a stored procedure, this represents the GraphQL operation to use, otherwise it will be null.</param>
/// <seealso cref="<https://engdic.org/singular-and-plural-noun-rules-definitions-examples/"/>
/// <remarks>
/// This type is mutable.
/// </remarks>
public class EntityGraphQLOptions
{
    public string Singular { get; set; }

    public string Plural { get; set; }

    public bool Enabled { get; set; }

    public GraphQLOperation? Operation { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityGraphQLOptions"/> class.
    /// </summary>
    /// <param name="singular">The singular type name for the GraphQL object. If none is provided this will be generated by the Entity key.</param>
    /// <param name="plural">The pluralisation of the entity. If none is provided a pluralisation of the Singular property is used.</param>
    /// <param name="enabled">Indicates if GraphQL is enabled for the entity.</param>
    /// <param name="operation">When the entity maps to a stored procedure, this represents the GraphQL operation to use, otherwise it will be null.</param>
    public EntityGraphQLOptions(string singular, string plural, bool enabled, GraphQLOperation? operation = null)
    {
        Singular = singular;
        Plural = plural;
        Enabled = enabled;
        Operation = operation;
    }
}
